/**
 * config/database.js
 *
 * PostgreSQL connection pool.
 *
 * WHY A POOL, NOT A SINGLE CONNECTION:
 *   A single pg.Client handles one query at a time. Under load, every request
 *   would queue behind the previous one. A Pool maintains up to `max` open
 *   connections and assigns idle ones to incoming queries. With two EC2
 *   instances each running this code, `poolMax: 10` means RDS will see at
 *   most 20 simultaneous connections — well within the default limit.
 *
 * WHY NOT pg-promise OR sequelize:
 *   Raw `pg` is explicit, fast, and has zero magic. You write SQL, you get
 *   rows back. For a gateway that runs a handful of known queries, an ORM
 *   adds complexity without benefit.
 *
 * PRODUCTION UPGRADE — IAM auth:
 *   On AWS, swap the password field for a short-lived IAM token generated by
 *   `rds-signer`. The pool's `password` option accepts a function that returns
 *   a promise, so token rotation is seamless. See infra/vpc-notes.md.
 */

const { Pool } = require('pg');
const config   = require('./index');
const logger   = require('../utils/logger');

// ─── Pool creation ────────────────────────────────────────────────────────────
const pool = new Pool({
  host:     config.postgres.host,
  port:     config.postgres.port,
  database: config.postgres.database,
  user:     config.postgres.user,
  password: config.postgres.password,
  max:      config.postgres.poolMax,

  // How long (ms) a client can sit idle in the pool before being closed.
  idleTimeoutMillis: 30_000,

  // How long (ms) to wait for a connection before throwing.
  connectionTimeoutMillis: 5_000,
});

// ─── Error handler ────────────────────────────────────────────────────────────
// This fires if an idle client hits a network error between queries.
// Without this listener, Node will throw an uncaught exception and crash.
pool.on('error', (err) => {
  logger.error({ err }, '[postgres] Unexpected client error — pool will recover');
});

// ─── testConnection ───────────────────────────────────────────────────────────
/**
 * Runs a trivial query to confirm the pool can reach Postgres.
 * Called once at startup by server.js — if this throws, the server won't start.
 * Also called by the /health endpoint on every request.
 */
async function testConnection() {
  const client = await pool.connect();
  try {
    await client.query('SELECT 1');
  } finally {
    client.release(); // always release back to pool, even on error
  }
}

module.exports = { pool, testConnection };
